Do not check mount point if virtualization gets detected.
More and more tools use containers instead of chroots to build OS
images. This change makes sure that the package installation works
within a container.

diff --git a/debian/kernel/postinst.d/raspi3-firmware b/debian/kernel/postinst.d/raspi3-firmware
--- a/debian/kernel/postinst.d/raspi3-firmware
+++ b/debian/kernel/postinst.d/raspi3-firmware
@@ -31,11 +31,13 @@ case "$1" in
     ;;
 esac
 
-if ! ischroot; then
-  if ! mountpoint -q /boot/firmware; then
-    echo "raspi3-firmware: missing /boot/firmware, did you forget to mount it?" >&2
-    exit 1
-  fi
+if ischroot ; then
+  true # chroot detected - skip mount point check
+elif test -e /usr/bin/systemd-detect-virt && systemd-detect-virt -q ; then
+  true # virtualization detected - skip mount point check
+elif ! mountpoint -q /boot/firmware; then
+  echo "raspi3-firmware: missing /boot/firmware, did you forget to mount it?" >&2
+  exit 1
 fi
 
 # Ensure the target directory exists. See https://bugs.debian.org/887062
